name: macos-latest

on:
  workflow_dispatch:
    inputs:
      authcode:
        description: "CRD Code"
        required: true
      pincode:
        description: "6 digit PIN"
        required: true

jobs:
  setup:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: setting permission
        run:  chmod u+x ./setup/macos-latest/setup.sh
      - name: setting permission
        run:  chmod u+x ./setup/macos-latest/timeout.sh
      - name: Initializing Setup
        run:  bash ./setup/macos-latest/setup.sh
      - name: Starting CRD
        run: ${{ github.event.inputs.authcode }} -pin=${{ github.event.inputs.pincode }}
      - name: Keep Alive
        run: bash ./setup/macos-latest/timeout.sh
