name: macos-latest

on:
  workflow_dispatch:
    inputs:
      authcode:
        description: "CRD Code"
        required: true
      pincode:
        description: "6 digit PIN"
        required: true

jobs:
  setup:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Initializing Setup
        run: ./macos-latest/setup.ps1
      - name: Starting CRD
        run: ${{ github.event.inputs.authcode }} -pin=${{ github.event.inputs.pincode }}
      - name: Keep Alive
        run: ./timeout.ps1
